frontend:
  repository_title: "Composer Repository"
  repository_for: "Spectware, Inc."
  repository_contact: "chris.westerfield@spectware.com"
  impressum: "Imprint: contact: chris.westerfield@spectware.com"

